"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var breakpoint_1 = require("./breakpoint");
exports.BreakPointManager = breakpoint_1.BreakPointManager;
exports.getClientWidth = breakpoint_1.getClientWidth;
exports.default = breakpoint_1.install;
var listener_1 = require("./listener");
exports.addEventListenerWithOptions = listener_1.addEventListenerWithOptions;
exports.createSafetyEventListenerOptions = listener_1.createSafetyEventListenerOptions;
exports.removeEventListenerWithOptions = listener_1.removeEventListenerWithOptions;
exports.supportsCaptureOption = listener_1.supportsCaptureOption;
